source 'https://github.com/CocoaPods/Specs.git'
platform:ios,'9.0'

target 'SwiftOnlineShopDemo' do

pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDCycleScrollView','~> 1.75'
pod 'RollingNotice'
pod 'Moya'

end
